### ISSUE TITLE
crash with Sandwichable and Minekea

### ISSUE THREAD

**Issue by AnomalousDeity** [chimericdream/minekea-fabric#65]
**Describe the bug**
a definite crash with the mod Sandwichable and Minekea

**To Reproduce**
1. place a display case
2. build a ridiculous Scooby doo size sandwich 
3. attempt to place inside display case
4. crash

**Expected behavior**
honestly im not sure what to expect, I was horsing around testing mods before I load it onto a server, decided ya know what imma make a sandwich taller than my own character which I did several times then decided if I could display it, got out the display case expecting some broken looking rendering Or it not to work at all but I got a crash, but well worth a good laugh seeing my absurd construction 

**Screenshots**

**Environment**
 * Minecraft version: fabric 1.19
 * Minekea version: 3.1.2
 * OS: Windows 10

**Additional context**
works fine with item frames, ill give a screenshot of my absurd sandwich size for reference or good laughs if it helps any
![Absurd sandwich](https://user-images.githubusercontent.com/91780401/183235437-a2862191-f4fb-46b8-96fd-418c0a312632.png)

**Comment by AnomalousDeity** [comment]
I like to also mention if you do this either back up your world or roll back because you wont be able to load your world up without crashing

**Comment by chimericdream** [comment]
I don't even know what to say to this. I am simultaneously horrified and in awe. I have no idea why it would crash in a display case but not an item frame (I copied parts of the item frame code related to rendering). But I'll definitely see if it's something I can fix.

Thanks for the report (and the chuckle)!

**Comment by AnomalousDeity** [comment]
heres the crash description if it helps as well honestly though I dont think the cases would be used to display the monstrous abomination that is my cursed sandwich but I also dont want to risk having to roll back to avoid corrupted worlds tho it was def fun finding this xD

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1922.method_8321(net.minecraft.class_2338)" because "view" is null
	at io.github.foundationgames.sandwichable.blocks.SandwichBlock.method_9530(SandwichBlock.java:46)
	at com.chimericdream.minekea.client.render.block.DisplayCaseBlockEntityRenderer.render(DisplayCaseBlockEntityRenderer.java:78)
	at com.chimericdream.minekea.client.render.block.DisplayCaseBlockEntityRenderer.method_3569(DisplayCaseBlockEntityRenderer.java:30)
	at net.minecraft.class_824.method_23079(class_824.java:90)
	at net.minecraft.class_824.method_23081(class_824.java:79)
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderBlockEntities(ShadowRenderer.java:549)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:471)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:644)
	at net.minecraft.class_761.handler$elp000$iris$renderTerrainShadows(class_761.java:12033)
	at net.minecraft.class_761.method_22710(class_761.java:1239)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by chimericdream** [comment]
Does everything work fine with a more human sized sandwich?

**Comment by AnomalousDeity** [comment]
Hm lemme try it real quick

**Comment by AnomalousDeity** [comment]
Ok no it doesnt, it works fine with item frames and shelves fine just not the display case

![2022-08-06_13 45 49](https://user-images.githubusercontent.com/91780401/183265540-8a35b054-a464-45e8-b0d4-1af94b0f5615.png)

![2022-08-06_13 46 40](https://user-images.githubusercontent.com/91780401/183265548-bd6bd643-2bb0-41d9-a782-8dcef6e1c1a2.png)

![2022-08-06_13 46 59](https://user-images.githubusercontent.com/91780401/183265556-812edb95-8ae6-453c-b10b-2e54f4b347dc.png)

**Comment by chimericdream** [comment]
I have this fixed locally and will be pushing an update for 1.19 and 1.19.1 today. Thanks for the report!
